name: film Scrape

on:
  push:
  schedule:
    - cron: "31 18 * * 3,4,6"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: '12.x'
      - run: npm install
      - name: Run script
        run: node ./utils/filmScrape.js
